  string
  datasource:
    url: jbdc:mysql://localhost:3306/back2?serverTimezone=UTC&usesSSL=false&allowPublicKeyRetrieve=True
    username: isaac
    password: 1025657584


  jpa:
    hibernate:
      dol-auto: update
    open-in-view: false

    properties:
      hibernate:
        format_sql: true