spring:
  datasource:
    url: jdbc:mysql://localhost:3306/back2?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieve=True
    username: isaac
    password: 1025657584

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true